FROM rasa/rasa-sdk:3.8.0

COPY ./actions_server/src /app/actions
COPY ./datasets /app/datasets

ARG ${PAT}

USER root

# install dotnet
RUN apt-get update && apt-get install -y wget apt-transport-https software-properties-common

RUN wget http://archive.ubuntu.com/ubuntu/pool/main/o/openssl/libssl1.1_1.1.0g-2ubuntu4_amd64.deb
RUN dpkg -i libssl1.1_1.1.0g-2ubuntu4_amd64.deb

RUN wget -q https://packages.microsoft.com/config/ubuntu/20.04/packages-microsoft-prod.deb
RUN dpkg -i packages-microsoft-prod.deb
RUN apt-get update && apt-get install -y dotnet-sdk-5.0

COPY requirements.txt /app/

RUN pip install -r /app/requirements.txt

USER 1001
