FROM rasa/rasa:3.6.18-full

WORKDIR /app

COPY ./rasa_chatbot /app

USER root
RUN pip install poetry==1.7.1 && \
    poetry install --without dev
RUN python -m spacy download en_core_web_lg
RUN rasa train

USER 1001

CMD ["run", "--enable-api", "--cors", "*"]
