version: '3.8'

services:
  rasa:
    dockerfile:
      context: .
      dockerfile: retailGPT/Dockerfile.rasa
    restart: unless-stopped

  actions:
    dockerfile:
      context: .
      dockerfile: retailGPT/Dockerfile.actions
    environment:
      - AZURE_OPENAI_API_KEY
      - AZURE_API_KEY 
      - OPENAI_API_KEY 
      - AZURE_LANGUAGE_KEY
    restart: unless-stopped

  demo:
    dockerfile:
      context: .
      dockerfile: chat_interface/Dockerfile
    ports:
      - "8501:8501"
    restart: unless-stopped

  database:
    image: redis
    ports:
      - "6379:6379"
    restart: unless-stopped